name: application-base-service

spring:
  main:
    allow-bean-definition-overriding: true
  profiles: default
  datasource:
    url: jdbc:h2:mem:sampleDB;
    driverClassName: org.h2.Driver
    username: admin
    password: 1q2w3e4r
    initialization-mode: always
    continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true
    format-sql: true
    id:
      new-generator-mapping: false
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:asdqwe123@localhost:8763/eureka/
      
application:
  flag: application-base-service-default
      
      