server:
  port: 8881
  
spring:
  application:
    name: config-service
  # https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # For Ubuntu
          search-locations: 
          - classpath:/application-base-service
          - classpath:/application-social-service
          - classpath:/auth-service
        #git:
        #  uri: https://github.com/code-presso/simplesns-config
        #  searchPaths: baseservice, socialservice
        #  username: code-presso
        #  password: CodePresso@3$5
  security:
    user:
      name: admin
      password: asdqwe123
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:asdqwe123@localhost:8763/eureka/