server:
  port: 8881
  
spring:
  application:
    name: config-service
  # https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html
  profiles:
    active: native,dev
  cloud:
    config:
      server:
        native:
          # For Ubuntu
          search-locations: 'file:/home/bkcha/workspace/sample codes/Spring Boot - MSA/config-service/src/main/resources/application-base-service,
                             file:/home/bkcha/workspace/sample codes/Spring Boot - MSA/config-service/src/main/resources/application-social-service,
                             file:/home/bkcha/workspace/sample codes/Spring Boot - MSA/config-service/src/main/resources/auth-service'
          #- classpath:/social-service
          # For windows
          #- C:/workspace/sample codes/Spring Boot - MSA/config-service/src/main/resources/baseService
          #- C:/workspace/sample codes/Spring Boot - MSA/config-service/src/main/resources/socialService
        #git:
        #  uri: https://github.com/code-presso/simplesns-config
        #  searchPaths: baseservice, socialservice
        #  username: code-presso
        #  password: CodePresso@3$5
  security:
    user:
      name: admin
      password: asdqwe123
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:asdqwe123@localhost:8763/eureka/